name: Pipeline
on: [push, pull_request] # O que faz o workflow ser executado

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'